sudo: false
cache: bundler
language: ruby
env:
  matrix:
    - SOLIDUS_BRANCH=v1.0   DB=postgres
    - SOLIDUS_BRANCH=v1.1   DB=postgres
    - SOLIDUS_BRANCH=v1.2   DB=postgres
    - SOLIDUS_BRANCH=master DB=postgres
script:
  - bundle exec rake test_app
  - bundle exec rspec
rvm:
  - 2.1.8
